return {}
--return {
--   'nvim-neorg/neorg',
--   lazy = false, -- Disable lazy loading as some `lazy.nvim` distributions set `lazy = true` by default
--   version = '*', -- Pin Neorg to the latest stable release
--   ft = 'norg',
--   priority = 30,
--   cmd = 'Neorg',
--   dependencies = {
--     { 'nvim-neorg/neorg-telescope' },
--   },
--   config = function()
--     require('neorg').setup {
--       load = {
--         ['core.defaults'] = {},
--         ['core.concealer'] = {},
--         ['core.completion'] = {
--           config = {
--             engine = 'nvim-cmp',
--           },
--         },
--         ['core.dirman'] = {
--           config = {
--             workspaces = {
--               notes = '~/Documents/notes/',
--             },
--             default_workspace = 'notes',
--           },
--         },
--         ['core.summary'] = {},
--         ['core.integrations.nvim-cmp'] = {},
--         ['core.integrations.telescope'] = {},
--       },
--     }
--     vim.wo.foldlevel = 90
--     vim.wo.conceallevel = 3
--   end,
-- }
